### ISSUE TITLE
Bug: Unity 프로젝트를 열었을 때, Safe Mode로 열림

### ISSUE THREAD

**Issue by derek-rtzr** [2021-metaverse-developer-contest/co-ex#162]
### 2020.3.17f
1. Library Samsung Adaptive Performance에서 문제 발생
2. firebase의 .meta 파일에서 문제를 발생시킴

### 2020.3.25f
1. Library Samsung Adaptive Performance에서 문제 발생

**Comment by exgs** [comment]
git lfs pull을 하지 않고 Unity Editor로 project를 열어서 생긴 문제, `.dll` 파일은 용량이 100MB가 넘기 때문에
root의 .gitattribute에서 lfs로 저장되도록 설정해두었기때문이다.
coex의 3D 맵을 git lfs 에 저장하지 않을 것이기때문에 #163 의 문제를 해결하면서, `.dll` 파일만 git lfs에 올리는 방안으로 계획예정
위 문제는 결국 실행전에 `git lfs pull`을 안했기때문에 발생한 실수이기때문에 #163 에서 모든 문제를 해결하는것으로 하겠음.

Related to: #163
