### ISSUE TITLE
Refactoring:  gif-lfs에 있는 모든 파일 내리기

### ISSUE THREAD

**Issue by derek-rtzr** [2021-metaverse-developer-contest/co-ex#163]
1. SSIA(Subject Say It All)
2. lfs 과금으로부터 자유로워지기위해서

**Comment by exgs** [comment]
1. `.gitattributes` 파일을 삭제한 후에 새로 클론을 받는다.
2. 기존의 git lfs 에 있는 파일주소만 적혀있는 파일을 git lfs pull을 통해서 실제 파일을 다운로드 받는 방식으로 rewrite한다.
    그 중에서 100MB가 넘는 파일은 임의로 빼주었다..(수작업 Ohno..)
3. git push를 해서, 리파짓토리에는 git lfs에 파일주소로 연결된 파일은 더이상 없다.

---

### 남은 목표
1. Billing 구독을 취소한다.
2. 잠시 빼두었던 파일을 다시 git lfs로 추가한다.

**Comment by exgs** [comment]
잘 되지않음.
Git lfs Server에 올라가있는 실제 파일의 데이터를 Flush 시켜야하는데, 방법이 쉽지않음.
### 문제상황
1. 포인터로 작성된 파일을 모두 실제 파일로 변환하는 커맨드가 있다고해도, 이전 히스토리에서 100MB가 넘어가는 파일을 어떻게 처리할지 감이 안잡힘
2. VPSData 때문에, 9GB나 쓰고 있는 것 같은데, 현재 master branch에서는 사용하고 있지않지만,
 `git lfs ls-files --all` 명령어로 확인하면, 특정 branch에서 사용하고 있는 것으로 보인다.
 ```
* -a --all:
  Inspects the full history of the repository, not the current HEAD (or other
  provided reference). This will include previous versions of LFS objects that
  are no longer found in the current tree.
  ```

**Comment by exgs** [comment]
1. git 명령어의 실행이 느린 것 같아서 Remote에 있는 branch 모두 삭제
2. git filter-branch를 한번 적용해서 remote 를 싹다 갈아 엎음
현재 HEAD에 해당하는 커밋에서는 크게 문제가 되지않으나, 커밋을 쌓으면서 처리되지않은 `VPSData/**` 가 있어서 아직도 9GB나 차지하고 이씀

---

다행인 것은 동작은 문제없이 돌아감

**Comment by exgs** [comment]
Gihub e-mail 문의로 git lfs remote files(9GB, mostly `VPSData/**` which is not thing we use..)를 모두 날렸다.
git lfs로 파일을 받아오던 `.jpg`, `.dll`, `.so` etc 와 같은 파일이 삭제되어 Unity로 열면 Safe Mode로 열림.  

## Todo
Seeing Log printed in Safe Mode, Fix the bug!

**Comment by exgs** [comment]
😄  해결완료 
Related: https://github.com/2021-metaverse-developer-contest/co-ex/compare/v.1.0...v.1.1
![Optimized-스크린샷 2022-04-16 오후 6 07 06](https://user-images.githubusercontent.com/56223639/163669185-76931228-dd8b-440b-a04f-c7d36eb834fd.png)
